services:
  jaeger-all-in-one:
    container_name: jaeger-all-in-one
    image: jaegertracing/all-in-one:latest
    restart: always
    ports:
      - "16686:16686" # Jaeger UI
      - "4317:4317" # OpenTelemetry gRPC
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - SPAN_STORAGE_TYPE=memory
      - MEMORY_MAX_TRACES=100000
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:16686" ]
      interval: 10s
      timeout: 5s
      retries: 5
    mem_limit: 1g
    networks:
      - backend

  postgres:
    image: "ankane/pgvector:v0.4.1"
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./someInit:/docker-entrypoint-someInit.d # 初始化 SQL 脚本
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin}
      POSTGRES_DB: ${POSTGRES_DB:-taxin}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    mem_limit: 1g
    command: postgres -c max_connections=200 -c shared_buffers=256MB
    networks:
      - backend


networks:
  backend:
    driver: bridge

volumes:
  postgres_data:
  redis_data: